In [1]:
!pip install beautifulsoup4
!pip install glob
!pip install pandas

Requirement already satisfied: beautifulsoup4 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (4.14.2)
Requirement already satisfied: soupsieve>1.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from beautifulsoup4) (4.14.0)
ERROR: Could not find a version that satisfies the requirement glob (from versions: none)
ERROR: No matching distribution found for glob
Requirement already satisfied: pandas in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/ryanxavier/miniforge3/envs/rag_poc/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
from bs4 import BeautifulSoup
import glob
import pandas as pd
import requests


key = "ea04f85bdd4b485c9c93f5faca413d05"
url = "https://newsapi.org/v2/top-headlines"  
cond = {"language": "en", "pageSize": 75, "apiKey": key}

call = requests.get(url, params=cond)
raw_art = call.json()
article_list = []
for a in raw_art.get("articles", []):
    raw_url = a.get("url")

    raw_text = None
    try:
        curr_art = requests.get(raw_url, timeout=15)
        s = BeautifulSoup(curr_art.text, "html.parser")

        paragraphs = [p.get_text() for p in s.find_all("p")]
        raw_text = " ".join(paragraphs)
    except Exception as e:
        raw_text = None
    article_list.append({
        "statement": raw_text
    })




df = pd.DataFrame(article_list)
df = df[df['statement'].notna() & (df['statement'].str.strip() != '')]

df

                                            statement
0   This live coverage has now ended - you can rea...
1   \n          Quotes displayed in real-time or d...
3    Now  46  Tue  54  Wed  58 by KONSTANTIN TOROP...
6   Copyright 2025 The Associated Press. All Right...
7   Watch CBS News \nOctober 27, 2025 / 12:05 PM E...
9   Ahead of an expected global launch in the comi...
10  By  \n\n      The Associated Press\n    \n \n ...
11  Guest Guest Login | Sign Up Push Square  Guest...
12  Civilian activist Mouawia had just escaped el-...
13          POPULAR ARTICLES LATEST PODCASTS View All
14  Cybersecurity researchers have discovered a ne...
15  \n\t\t\t\t\tBy Ted Johnson  Political Editor \...
16  The chemical signatures we're observing may re...
17  Writer Sunday's game against the Chicago Bears...
20  Singer Katy Perry and former Canadian Prime Mi...
21  \nReference #18.571ca17.1761679424.13ff57fe\nh...
22  \nReference #18.571ca17.1761679424.13ff58b9\nh...
23  \n            Despite Week 8 in the 2025 NFL s...
24  When astronomers want to see the finest detail...
25  \n            Air traffic controller staffing ...
26  \n \n\t\t\t\t\t\t\t\tBy \n\n\tMarc Malkin\n Se...
27  You have been rate-limited for making too many...
28  The TOI Lifestyle Desk is a dynamic team of de...
29  No corporate owners. No outside agenda. Hawks ...

In [7]:
df['statement'] = (
    df['statement']
    .astype(str)  
    .str.replace(r'\s+', ' ', regex=True) 
    .str.strip() 
)

In [8]:
df

                                            statement
0   This live coverage has now ended - you can rea...
1   Quotes displayed in real-time or delayed by at...
3   Now 46 Tue 54 Wed 58 by KONSTANTIN TOROPIN, As...
6   Copyright 2025 The Associated Press. All Right...
7   Watch CBS News October 27, 2025 / 12:05 PM EDT...
9   Ahead of an expected global launch in the comi...
10  By The Associated Press Catherine Connolly smi...
11  Guest Guest Login | Sign Up Push Square Guest ...
12  Civilian activist Mouawia had just escaped el-...
13          POPULAR ARTICLES LATEST PODCASTS View All
14  Cybersecurity researchers have discovered a ne...
15  By Ted Johnson Political Editor Donald Trump a...
16  The chemical signatures we're observing may re...
17  Writer Sunday's game against the Chicago Bears...
20  Singer Katy Perry and former Canadian Prime Mi...
21  Reference #18.571ca17.1761679424.13ff57fe http...
22  Reference #18.571ca17.1761679424.13ff58b9 http...
23  Despite Week 8 in the 2025 NFL season being du...
24  When astronomers want to see the finest detail...
25  Air traffic controller staffing shortages wors...
26  By Marc Malkin Senior Editor, Culture and Even...
27  You have been rate-limited for making too many...
28  The TOI Lifestyle Desk is a dynamic team of de...
29  No corporate owners. No outside agenda. Hawks ...