In [1]:
from bs4 import BeautifulSoup
from newspaper import Article
import glob
import pandas as pd
import requests


key = "ea04f85bdd4b485c9c93f5faca413d05"
url = "https://newsapi.org/v2/everything"  
topic = "Columbus Day"
cond = {"q": topic,"language": "en", "pageSize": 75, "apiKey": key, "sortBy": "relevancy"}

call = requests.get(url, params=cond)
raw_art = call.json()
article_list = []
for a in raw_art.get("articles", []):
    raw_url = a.get("url")

    raw_text = None
    try:
        curr_art = Article(raw_url)
        curr_art.download()
        curr_art.parse()
        raw_text = curr_art.text
        s = BeautifulSoup(curr_art.text, "html.parser")
    except Exception as e:
        raw_text = None
    
    article_list.append({
        "statement": raw_text
    })




df = pd.DataFrame(article_list)
df = df[df['statement'].notna() & (df['statement'].str.strip() != '')]

df

                                            statement
0   Trump issues a Columbus Day proclamation to 'r...
1   Keeper of the Ashes: The Oklahoma Girl Scout M...
2   This story is available exclusively to Busines...
4   NOTE: I'm on vacation returning next week. Gov...
5   AI-assisted summary A frost advisory was issue...
6   VATICAN CITY (AP) — Pope Leo XIV has begun cor...
7   President Donald Trump reignited a familiar cu...
8   Apple plans to announce new products "this wee...
9   Although it's officially fall, Greater Cincinn...
10  This story is available exclusively to Busines...
11  The U.S. government recognizes the second Mond...
12  Columbus Day is almost here and we can expect ...
13  Director Chris Columbus lamented earlier this ...
14  DNA-synthesis firms routinely use -biosecurity...
15  EXCLUSIVE: Nightmares Film Festival has unveil...
16  A Mini-Vacay In Columbus: Part 2\n\nFor my and...
17  The NYC Marathon was first run in 1970, when 1...
18  Actress and activist Frances Fisher punked Don...
19  Open Extended Reactions\n\nMIAMI -- It was a l...
20  Battles over Columbus Day aren’t really about ...
21  Who came out on top in the fake news battle?\n...
22  Unwinding At Panacea Luxury Spa In Columbus\n\...
24  Activism / Renaming Columbus Day Was Never the...
36  Former Yankees first baseman Mark Teixeira has...
46  The Trump lickspittles on Fox & Friends Weeken...
47  A Mini-Vacay In Columbus: Part 1\n\nI know I’v...
48  WASHINGTON–President Donald Trump kicked off T...
51  Greetings, Dear Reader,\n\nI grew up in an Ita...
52  With the images they capture at Terminal Islan...
53  The federal government shutdown has entered it...
54  While the stock market closes for many federal...
55  Stock futures are soaring this morning after P...
56  Senate Majority Leader John Thune of South Dak...
57  If you are reading this, odds are you know tha...
58  October 3, 2025: I cannot believe the impact t...
59  THE CENTER SQUARE—Outgoing New York City Mayor...
60  “We’re back. Columbus Day. We’re back, Italian...
61  Mikkel Uhre scores the match's lone goal as Ph...
63  President Donald Trump signed a proclamation T...
64  Over the past two decades or so, we have witne...
65  The wind and rain is expected to bring floodin...
66  Two activists affiliated with the Spanish clim...
67  A Year Of Blogging\n\nOctober 1st of 2024 was ...
69  A quartet of fall season arrivals began previe...
70  The final day of the MLS season came and went,...
71  Back in 1492, Christopher Columbus sailed the ...
72  Some traders will get a break on Monday. Just ...

In [5]:
article_list = []
for a in raw_art.get("articles", []):
    raw_url = a.get("url")
    source_name = a.get("source", {}).get("name", "Unknown")
    
    raw_text = None
    try:
        curr_art = Article(raw_url)
        curr_art.download()
        curr_art.parse()
        raw_text = curr_art.text
    except Exception as e:
        raw_text = None
    
    article_list.append({
        "statement": raw_text,
        "source": source_name
    })

df = pd.DataFrame(article_list)
df = df[df['statement'].notna() & (df['statement'].str.strip() != '')]
df

                                            statement                   source
0   Trump issues a Columbus Day proclamation to 'r...                      NPR
1   Keeper of the Ashes: The Oklahoma Girl Scout M...                 ABC News
2   This story is available exclusively to Busines...         Business Insider
4   NOTE: I'm on vacation returning next week. Gov...   Calculatedriskblog.com
5   AI-assisted summary A frost advisory was issue...              Fci Academy
6   VATICAN CITY (AP) — Pope Leo XIV has begun cor...      Yahoo Entertainment
7   President Donald Trump reignited a familiar cu...                    Salon
8   Apple plans to announce new products "this wee...                MacRumors
9   Although it's officially fall, Greater Cincinn...  The Cincinnati Enquirer
10  This story is available exclusively to Busines...         Business Insider
11  The U.S. government recognizes the second Mond...               Snopes.com
12  Columbus Day is almost here and we can expect ...      Americanthinker.com
13  Director Chris Columbus lamented earlier this ...              Cracked.com
14  DNA-synthesis firms routinely use -biosecurity...               Nature.com
15  EXCLUSIVE: Nightmares Film Festival has unveil...                 Deadline
16  A Mini-Vacay In Columbus: Part 2\n\nFor my and...               Scalzi.com
17  The NYC Marathon was first run in 1970, when 1...          NorthJersey.com
18  Actress and activist Frances Fisher punked Don...       Crooksandliars.com
19  Open Extended Reactions\n\nMIAMI -- It was a l...                     ESPN
20  Battles over Columbus Day aren’t really about ...             Daily Signal
21  Who came out on top in the fake news battle?\n...              Cracked.com
22  Unwinding At Panacea Luxury Spa In Columbus\n\...               Scalzi.com
24  Activism / Renaming Columbus Day Was Never the...            Thenation.com
36  Former Yankees first baseman Mark Teixeira has...                   nj.com
46  The Trump lickspittles on Fox & Friends Weeken...       Crooksandliars.com
47  A Mini-Vacay In Columbus: Part 1\n\nI know I’v...               Scalzi.com
48  WASHINGTON–President Donald Trump kicked off T...           Breitbart News
51  Greetings, Dear Reader,\n\nI grew up in an Ita...         The Daily Caller
52  With the images they capture at Terminal Islan...           The New Yorker
53  The federal government shutdown has entered it...             Daily Signal
54  While the stock market closes for many federal...   The Providence Journal
55  Stock futures are soaring this morning after P...             Investopedia
56  Senate Majority Leader John Thune of South Dak...         The Daily Caller
57  If you are reading this, odds are you know tha...             Wonkette.com
58  October 3, 2025: I cannot believe the impact t...            Wjgilmore.com
59  THE CENTER SQUARE—Outgoing New York City Mayor...             Daily Signal
60  “We’re back. Columbus Day. We’re back, Italian...             Daily Signal
61  Mikkel Uhre scores the match's lone goal as Ph...                     ESPN
63  President Donald Trump signed a proclamation T...                 Mediaite
64  Over the past two decades or so, we have witne...    Legalinsurrection.com
65  The wind and rain is expected to bring floodin...                Gothamist
66  Two activists affiliated with the Spanish clim...            Hyperallergic
67  A Year Of Blogging\n\nOctober 1st of 2024 was ...               Scalzi.com
69  A quartet of fall season arrivals began previe...                 Deadline
70  The final day of the MLS season came and went,...               CBS Sports
71  Back in 1492, Christopher Columbus sailed the ...           Babylonbee.com
72  Some traders will get a break on Monday. Just ...             Investopedia

In [2]:
print(df.loc[0, 'statement'])

Trump issues a Columbus Day proclamation to 'reclaim' the explorer's legacy

toggle caption Anna Moneymaker/Getty Images

President Trump has signed a proclamation declaring Monday to be Columbus Day, in an effort to "reclaim" what he called the famed explorer's "extraordinary legacy of faith, courage, perseverance, and virtue."

The proclamation comes after Trump said in a social media post in April that, to

bring the holiday "back from the ashes," he would reinstate "Columbus Day under the same rules, dates, and locations, as it has had for all of the many decades before!"

In recent years, many people have instead celebrated Indigenous Peoples Day to recognize Native land and acknowledge the contributions Native Americans have made to the country.

Critics and advocates like Kerri Malloy, a professor of Native American and Indigenous Studies at San José State University, have challenged Columbus Day and Columbus' legacy. He says Columbus' arrival to the Americas "triggered a mass genocide of Indigenous people throughout the Western hemisphere," which included deadly diseases being spread among them, their land being stolen and being forced into Christianity.

Sponsor Message

Thursday's proclamation does not mention Indigenous Peoples Day, but it accuses "left-wing arsonists" of trying to "destroy [Columbus'] name and dishonor his memory."

Columbus Day is one of 12 federally recognized holidays in 2025. According to the Pew Research Center, 30 states and three U.S. territories recognize Columbus Day in some way, while 17 states and D.C. commemorate Indigenous people on that day. Included in those tallies are the several states that recognize both. In 2021, Joe Biden became the first president to officially recognize Indigenous Peoples Day on the same date as Columbus Day.

Christopher Columbus was born in Italy in 1451 and sailed to what he thought would be Asia in 1492, with support from the Spanish monarchy. He instead arrived in what is now the Bahamas. He would make three more voyages to South America, Central America and the Caribbean before his death, but never made it to what is now the U.S., according to Britannica.

President Benjamin Harrison first commemorated Columbus Day in 1892, a year after anti-Italian rhetoric culminated in the murder of 11 Italian immigrants in New Orleans by a lynch mob. The attack put a strain on the relationship between Italy and the U.S., and the holiday was an olive branch. President Franklin Roosevelt proclaimed it a federal holiday in 1934.

Sponsor Message

After signing the document on Thursday, Trump said, "We're back, Italians. We love the Italians."

Rep. Elise Stefanik, a New York Republican, lauded his proclamation, writing on X, "New Yorkers [love] Columbus Day!"

Rep. Mike Lawler, a New York Republican and Italian American, said on X , "Viva Italia! As a proud Italian-American, I fully support protecting Columbus Day and celebrating the rich history and contributions of Italian-Americans."

Others weren't as enthused.

"The proclamation reiterates the American fantasy of Columbus' voyage, as solely a story of discovery and exploration, versus what it really was about — commerce and the exploitation of resources," said Malloy, the San José State professor. "You can't tell a story without telling both sides of it."

Still, the president is encouraging Americans to celebrate Columbus in some way on the holiday, and display the U.S. flag on all public buildings.

"This is the president trolling people of color, underrepresented minorities that tend not to vote for his party or candidacy," said Matthew Fletcher, director of the Indigenous Law and Policy Center at Michigan State University. "My sense is there's not a massive groundswell in favor of Columbus Day anymore, except, possibly, the Italian Americans."

Fletcher said that regardless of what the day is called, Indigenous people will still celebrate and be celebrated.

"It's local, it's tribal, it's statewide in a lot of places, and it's still going to be a legitimate thing, and people take it seriously," he said.

In [3]:
df['statement'] = (
    df['statement']
    .astype(str)  
    .str.replace(r'\s+', ' ', regex=True) 
    .str.strip() 
)

In [4]:
df

                                            statement
0   Trump issues a Columbus Day proclamation to 'r...
1   Keeper of the Ashes: The Oklahoma Girl Scout M...
2   This story is available exclusively to Busines...
4   NOTE: I'm on vacation returning next week. Gov...
5   AI-assisted summary A frost advisory was issue...
6   VATICAN CITY (AP) — Pope Leo XIV has begun cor...
7   President Donald Trump reignited a familiar cu...
8   Apple plans to announce new products "this wee...
9   Although it's officially fall, Greater Cincinn...
10  This story is available exclusively to Busines...
11  The U.S. government recognizes the second Mond...
12  Columbus Day is almost here and we can expect ...
13  Director Chris Columbus lamented earlier this ...
14  DNA-synthesis firms routinely use -biosecurity...
15  EXCLUSIVE: Nightmares Film Festival has unveil...
16  A Mini-Vacay In Columbus: Part 2 For my and Br...
17  The NYC Marathon was first run in 1970, when 1...
18  Actress and activist Frances Fisher punked Don...
19  Open Extended Reactions MIAMI -- It was a litt...
20  Battles over Columbus Day aren’t really about ...
21  Who came out on top in the fake news battle? S...
22  Unwinding At Panacea Luxury Spa In Columbus Ba...
24  Activism / Renaming Columbus Day Was Never the...
36  Former Yankees first baseman Mark Teixeira has...
46  The Trump lickspittles on Fox & Friends Weeken...
47  A Mini-Vacay In Columbus: Part 1 I know I’ve b...
48  WASHINGTON–President Donald Trump kicked off T...
51  Greetings, Dear Reader, I grew up in an Italia...
52  With the images they capture at Terminal Islan...
53  The federal government shutdown has entered it...
54  While the stock market closes for many federal...
55  Stock futures are soaring this morning after P...
56  Senate Majority Leader John Thune of South Dak...
57  If you are reading this, odds are you know tha...
58  October 3, 2025: I cannot believe the impact t...
59  THE CENTER SQUARE—Outgoing New York City Mayor...
60  “We’re back. Columbus Day. We’re back, Italian...
61  Mikkel Uhre scores the match's lone goal as Ph...
63  President Donald Trump signed a proclamation T...
64  Over the past two decades or so, we have witne...
65  The wind and rain is expected to bring floodin...
66  Two activists affiliated with the Spanish clim...
67  A Year Of Blogging October 1st of 2024 was my ...
69  A quartet of fall season arrivals began previe...
70  The final day of the MLS season came and went,...
71  Back in 1492, Christopher Columbus sailed the ...
72  Some traders will get a break on Monday. Just ...